### PR TITLE
Prefer 'uname -m' over 'uname -i'

### PR DESCRIPTION
**Pull request by jkachmar**
'uname -i' isn't portable, and its output can vary by distro.

'uname -m' has a POSIX specification, and should always return the machine architecture.

cf. https://pubs.opengroup.org/onlinepubs/9699919799/utilities/uname.html

### CODE REVIEW

**Comment by jkachmar** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by jeremyfowers — APPROVED** [review]
Works for me if the tests pass!

@ramkrishna2910 works for you?

**Review by ramkrishna2910 — APPROVED** [review]
lgtm!

**Review by danielholanda — APPROVED** [review]
Even works on mac. Fun!

**Pull request merged**
