### PR TITLE
Update diffusers version requirement

### PR DESCRIPTION
**Pull request by BowenBao**
Otherwise hits below error if diffusers >= 0.13
```
  File "/mla_bench/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 63, in <module>
    from transformers.utils import SAFE_WEIGHTS_NAME as TRANSFORMERS_SAFE_WEIGHTS_NAME
ImportError: cannot import name 'SAFE_WEIGHTS_NAME' from 'transformers.utils' (/mla_bench/lib/python3.10/site-packages/transformers/utils/__init__.py)
```

Another option is to bump `transformers` version. I have not done that since it is currently limited to `4.22.1` by requirements from `detoxify`

### CODE REVIEW

**Review by danielholanda — APPROVED** [review]
Thanks for the PR @BowenBao!
Limiting the `diffusers` library version seems like a good solution for now.
As you suggested, we should bump `transformers` version in the future once that works well with detoxify. 
Approved!

**Comment by danielholanda** [comment]
@BowenBao Thanks again for the PR. The GitHub Bot should allow you to merge this as soon as you comment "I have read the CLA Document and I hereby sign the CLA". 

If you have any other suggestions/PRs, please keep submitting them here and we will be happy to review them!

**Comment by BowenBao** [comment]
@danielholanda thanks, I'll check with my team regarding CLA and will get back to you! Btw the CLA link [Contributor License Agreement](https://github.com/groq/groqflow/cla.md) is showing not found. Perhaps it should be https://github.com/groq/mlagility/blob/main/cla.md?

**Comment by danielholanda** [comment]
Sounds good @BowenBao. Yes, https://github.com/groq/mlagility/blob/main/cla.md is the right file. I will make sure to update the link.

**Comment by jeremyfowers** [comment]
@BowenBao https://github.com/groq/mlagility/pull/273 removes the requirement for you to sign a CLA. If you update your branch all the checks should pass and you should be clear to merge this PR 😄

**Comment by BowenBao** [comment]
@jeremyfowers Awesome!

**Review by jeremyfowers — APPROVED** [review]

**Comment by jeremyfowers** [comment]
I'm trying to figure out why the PyPI action isn't running for you. It's configured a little differently... digging in...

**Comment by jeremyfowers** [comment]
> I'm trying to figure out why the PyPI action isn't running for you. It's configured a little differently... digging in...

Fixed 😸

**Pull request merged**
